### ISSUE TITLE
I can't downgrade my Vita to below the original minfw.

### ISSUE THREAD

**Issue by pettiagalla** [SKGleba/mincg#1]
I changed slim minfw(originally 3.09) to 02.16E7.90 and PSTV minfw(originally 3.30) to 02.1AB5.0E.
(Slim is 3.72, PSTV is 3.60Enso.)
I tried to downgrade two Vitas to 3.00 with modoru because I just wanted to test mincg.

However, on PSTV, the following error occurs when moving to the System Update screen and restarts when OK is pressed.
[This system software cannot be used with your PS Vita system. (C1-6562-9)]
On the other hand, FW installed successfully on slim, but the system information shows 3.72 instead of 3.00.

**Comment by Princess-of-Sleeping** [comment]
use modoru.
You cannot downgrade with regular system updates

**Comment by Princess-of-Sleeping** [comment]
~~PS TV will be released on November 14, 2013.
The release date of FW3.00 is November 5, 2013.
PS TV does not support 3.00 at hardware level
maybe..~~

FW 2.60 : Default release firmware for the PlayStation Vita TV in Japan.

**Comment by Princess-of-Sleeping** [comment]
P.S
C1-6562-9
0x800f0237
SCE_SBL_ERROR_SL_ESYSVER

**Comment by Princess-of-Sleeping** [comment]
@pettiagalla Check PUP to see if you really downgraded to 3.00

**Comment by KuromeSan** [comment]
I recall reading in the SCE SDK that the lowest pstv firmware is 3.00 ..

**Comment by LiEnby** [comment]
In the "DevKit_TestKit_Setup_Guide_e.pdf" from SCE SDK
it says the following:

> Version Down of the System Software
> When the Settings application of the DevKit system software is set as ★Debug Settings > Boot
> Parameters > PS TV Emulation > On, lowering the version to one less than system software 3.000 will
> return an error. When lowering the system software version to less than 3.000, set PS TV Emulation Off. 

[DevKit_TestKit_Setup_Guide_e.pdf](https://github.com/SKGleba/mincg/files/3822144/DevKit_TestKit_Setup_Guide_e.pdf)

this would imply PSTV's do not support anything lower than 3.00.

**Comment by pettiagalla** [comment]
I downloaded the PUP from the darthsternie archive and did a hash check....
I tried to downgrade PSTV to 3.01/3.10/3.18 but the same error occurred.

Slim is ....... brick xD lol
I knew that fw at the time of slim release was 2.50, so I thought it was possible to downgrade to 2.60.
However, nothing is displayed on the screen after installation. (black screen)
The power light is green and will not turn off even if press and hold the power button.
I unpluged the battery cable to turn off the power.

**Comment by LiEnby** [comment]
@pettiagalla in theroy only the LED screen would not show anything but it would still work? 
maybe you can hold the combo for safe mode and do all the button presses to get to "update system software"  without acturally seeing the screen?

if not u fucked

**Comment by pettiagalla** [comment]
@KuromeSan 
ok. I did it while put the fat vita next to the slim.
I tried updating from PC/Game card, but nothing happens.

**Comment by SKGleba** [comment]
```- You should NOT downgrade below 3.60 there may be some hardware differences on lower firmwares```

**Comment by StepS-** [comment]
Like already said, there may be hardware differences between different revisions of the same edition vita. Slims released later may have had their mainboard / other components upgraded. Older firmwares would not have the drivers that support those newer components.
Before attempting downgrading that low, a hardware table must be created, similar to TA-xxx on the PSP, that shows when support for each hardware component was added.

**Comment by CelesteBlue-dev** [comment]
Come on don't let people brick anymore
minimal HW FW (theory not tested yet):
FAT retail 1.00
SLIM retail 3.30
PSTV retail 2.60
