### ISSUE TITLE
No SMI files in UX0:data

### ISSUE THREAD

**Issue by ScareFeratis** [SKGleba/mincg#2]
Log contents:

mincg started!
fw: 0x3600000
OP_REQ[R]: 0x1
debugging mode [off]

VERIFY_SMI:START
fopread_err1
reading own leaf! (??)
read_leaf: 0x0
decrypting SMI... 0x0
Results:
INIT: 0x0
DKEY1_B: 0x0
DKEY1_C: 0x0
CPY_KEY1: 0x0
DEC_1: 0x0
CPY_SB: 0x0
RSA_CHK: 0x0
DKEY2_B: 0x0
DKEY2_C: 0x0
CPY_KEY2: 0x0
DEC_2: 0x0
FW_CHK: 0x1060000
VERIFY_SMI:OK!

WRITE_SMI:START
write_leaf: 0x0
WRITE_SMI:OK!

mincg finished!

**Comment by CelesteBlue-dev** [comment]
You must not select VERIFY SMI but instead DUMP SMI.

**Comment by ScareFeratis** [comment]
I'm doing EXACTLY that.

**Comment by CelesteBlue-dev** [comment]
If you want better support please come to Discord or Twitter.

**Comment by ScareFeratis** [comment]
Ahh, issue solved. I had my X/O remapped. Silly me.
